export const CREATE_USER = "CREATE_USER";
export const CREATE_CR_USER = "CREATE_CR_USER";
export const LOGIN_USER = "LOGIN_USER";
export const CHECK_AUTHENTICATION = "CHECK_AUTHENTICATION";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const DELETING_USER = "DELETING_USER";
export const USER_DELETED = "USER_DELETED";
export const UPDATING_USER = "UPDATING_USER";
export const USER_UPDATED = "USER_UPDATED";


//timetable actions
export const SET_TABLE_PAGE = "SET_TABLE_PAGE"

//subject actions
export const SUBJECT_TEMPLATE_CREATED = "SUBJECT_TEMPLATE_CREATED";
export const CREATING_SUBJECT = "CREATING_SUBJECT";
export const SUBJECT_CREATED = "SUBJECT_CREATED";
export const SUBJECT_LOADING = "SUBJECT_LOADING";
export const SUBJECT_LOADED = "SUBJECT_LOADED";
export const CLICKED_ADD_SUBJECT = "CLICKED_ADD_SUBJECT";
// export const SUBJECT_FETCH_SUCCESS = "SUBJECT_FETCH_SUCCESS";
export const SUBJECT_FETCH_ERROR = "SUBJECT_FETCH_ERROR";
export const CLEAR_SUBJECTS = "CLEAR_SUBJECTS";
export const DELETING_SUBJECT = "DELETING_SUBJECT";
export const SUBJECT_DELETED = "SUBJECT_DELETED";
export const UPDATING_SUBJECT = "UPDATING_SUBJECT";
export const SUBJECT_UPDATED = "SUBJECT_UPDATED";
export const CLEAR_EVENTS = "CLEAR_EVENTS";
export const LOADING_SEMESTER = "LOADING_SEMESTER";
export const SEMESTER_LOADED = "SEMESTER_LOADED";

//attendance actions
export const CREATING_ATTENDANCE = "CREATING_ATTENDANCE";
export const ATTENDANCE_CREATED = "ATTENDANCE_CREATED";
export const DELETING_ATTENDANCE = "DELETING_ATTENDANCE";
export const ATTENDANCE_DELETED = "ATTENDANCE_DELETED";
export const UPDATING_ATTENDANCE = "UPDATING_ATTENDANCE";
export const ATTENDANCE_UPDATED = "ATTENDANCE_UPDATED";
export const LOADING_ATTENDANCE = "LOADING_ATTENDANCE";
export const ATTENDANCE_LOADED = "ATTENDANCE_LOADED";
export const CLEAR_ATTENDANCE = "CLEAR_ATTENDNACE";
export const LOADING_ALL_SEMESTER = "GETTING_ALL_SEMESTER";
