export const CREATE_USER = "CREATE_USER";
export const CREATE_CR_USER = "CREATE_CR_USER";
export const LOGIN_USER = "LOGIN_USER";
export const CHECK_AUTHENTICATION = "CHECK_AUTHENTICATION";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const DELETING_USER = "DELETING_USER";
export const USER_DELETED = "USER_DELETED";


//subject actions
export const CREATE_SUBJECT_TEMPLATE = "CREATE_SUBJECT_TEMPLATE";
export const CREATING_SUBJECT = "CREATING_SUBJECT";
export const SUBJECT_CREATED = "SUBJECT_CREATED";
export const SUBJECT_LOADING = "SUBJECT_LOADING";
export const SUBJECT_LOADED = "SUBJECT_LOADED";
export const SUBJECT_FETCH_SUCCESS = "SUBJECT_FETCH_SUCCESS";
export const SUBJECT_FETCH_ERROR = "SUBJECT_FETCH_ERROR";
export const CLEAR_SUBJECTS = "CLEAR_SUBJECTS";

//attendance actions
